export const CHANGE_CURRENT_SONG_DETAILS = "CHANGE_CURRENT_SONG_DETAILS"
export const CHANGE_LYRIC_LIST = 'CHANGE_LYRIC_LIST'

export const CHANGE_CURRENT_SONG_INDEX = 'CHANGE_CURRENT_SONG_INDEX'
export const CHANGE_PLAY_LIST = 'CHANGE_PLAY_LIST'

export const CHANGE_PLAY_SEQUENCE = 'CHANGE_PLAY_SEQUENCE'
